### ISSUE TITLE
No downloadable plugin for Creator 4.9.1

### ISSUE THREAD

**Issue by petermost** [CoatiSoftware/qtc-sourcetrail#11]
When I install the plugin, I get an error dialog saying:
Could not resolve dependency 'Core(4.8.0)'
Could not resolve dependency 'CppEditor(4.8.0)'

I've tried the plugin [qtc-sourcetrail-osx-x64-qtc4.8.zip](https://github.com/CoatiSoftware/qtc-sourcetrail/releases/download/0.7/qtc-sourcetrail-osx-x64-qtc4.8.zip)
which most likely will not work with 4.9.1.

So basically the same problem as [Downloadable plugin works not for 4.7.0](https://github.com/CoatiSoftware/qtc-sourcetrail/issues/2)

**Comment by mlangkabel** [comment]
Fixed with merge of pull request #12.
