### ISSUE TITLE
No downloadable plugin for QTC 4.10.2

### ISSUE THREAD

**Issue by mmcgirr** [CoatiSoftware/qtc-sourcetrail#14]
When I install the plugin, I get an error dialog saying:
Could not resolve dependency 'Core(4.9.0)'
Could not resolve dependency 'CppEditor(4.9.0)'

I've tried the plugin qtc-sourcetrail-windows-x64-qtc4.9.zip
which most likely will not work with 4.10.2.

So basically the same problem as [No Downloadable plugin for 4.9.1](https://github.com/CoatiSoftware/qtc-sourcetrail/issues/11)

**Comment by mlangkabel** [comment]
fixed with merge of pull request #15
