### ISSUE TITLE
Downloadable plugin works not for 4.7.0

### ISSUE THREAD

**Issue by petermost** [CoatiSoftware/qtc-sourcetrail#2]
When I install the plugin, I get error messages saying:
Could not resolve dependency 'Core(4.4.0)'
Could not resolve dependency 'CppEditor(4.4.0)'

I've tried building it myself and changed in build.sh the download paths, but got then a compiler error:
src/sourcetrailplugin.cpp:37:10: fatal error: coreplugin/statusbarwidget.h: No such file or directory
 #include <coreplugin/statusbarwidget.h>

I'm attaching the changed build.sh, but I had to rename it, otherwise I can't upload it here.
[build.sh.txt](https://github.com/CoatiSoftware/qtc-sourcetrail/files/2337878/build.sh.txt)

**Comment by dhallas** [comment]
I think this has been solved now, at least I am now running with the plugin against Qt Creator 4.7. Please update this issue if you are still experiencing problems :)

**Comment by mlangkabel** [comment]
I think so, too. We should issue a new release that provides builds for all the newly supported QT Creator versions (including 4.7) and close this issue afterwards.

@dhallas: Do you have any remaining pull requests that you would like to have included in that release?

**Comment by dhallas** [comment]
Nope, I don't have any other things pending :)

**Comment by mlangkabel** [comment]
Alright, we'll issue a new release in a minute.

**Comment by mlangkabel** [comment]
New release is done, thanks again @dhallas!

**Comment by petermost** [comment]
It works for me too! Thank you :smiley:
