### ISSUE TITLE
wrong PluginsPath

### ISSUE THREAD

**Issue by bam80** [CoatiSoftware/qtc-sourcetrail#22]
https://github.com/CoatiSoftware/qtc-sourcetrail#install

> Download the libary from Releases and put it into the qtcreator plugins folder. To find out where the folder is located please check Help -> System Information... -> PluginsPath

It's wrong path.
On my machine:
`  PluginsPath: /var/home/bam/Qt/Tools/QtCreator/lib/Qt/plugins`

Path needed:
`/var/home/bam/Qt/Tools/QtCreator/lib/qtcreator/plugins/`

The needed path is not present anywhere in Help -> System Information...
Was it there earlier ever?

**Comment by mlangkabel** [comment]
Hm... I can find it in that dialog on Windows:
![image](https://user-images.githubusercontent.com/16242920/99559266-e1968900-29c4-11eb-9801-23e84a64fb94.png)

**Comment by davidscn** [comment]
I can confirm. Installing qt using `apt` on Ubuntu requires the following path:
`/usr/lib/x86_64-linux-gnu/qtcreator/plugins` whereas the system information shows `/usr/lib/x86_64-linux-gnu/qt5/plugins`. A quick search for other installed plugins and their respective location should help to find the correct location.

**Comment by dyl0010** [comment]
> Hm... I can find it in that dialog on Windows:
> ![image](https://user-images.githubusercontent.com/16242920/99559266-e1968900-29c4-11eb-9801-23e84a64fb94.png)

Windows 10 (Qt 5.14.1)下我放在这个路径并不起作用，放在**D:\Qt\Qt5.14.1\Tools\QtCreator\lib\qtcreator\plugins**时qtc可以检测到。

**Comment by mlangkabel** [comment]
Solved by merge of pull request #23.

**Comment by bam80** [comment]
Considering https://github.com/CoatiSoftware/qtc-sourcetrail/pull/23#discussion_r473268145, shall we reopen it again?

**Comment by mlangkabel** [comment]
Looks like it is different everywhere and with different version. Maybe we shouldn't write any specific path.

**Comment by bam80** [comment]
Yes, at least provide instruction how that path can be deduced manually..
